const a = [
  {
    id: 21,
    name: "",
    url: "",
    order: 23,
    type: 3,
    is_active: true,
    parent_id: 0,
  },
  {
    id: 1,
    name: "Introduction2",
    url: "",
    order: 100,
    type: 1,
    is_active: true,
    parent_id: 0,
  },
  {
    id: 3,
    name: "Терроризмтой тэмцэх зөвлөл",
    url: "",
    order: 110,
    type: 3,
    is_active: true,
    parent_id: 1,
  },
  {
    id: 5,
    name: "menu-1-1-2",
    url: "",
    order: 114,
    type: 1,
    is_active: true,
    parent_id: 3,
  },
  {
    id: 4,
    name: "menu-1-1-1",
    url: "",
    order: 115,
    type: 1,
    is_active: true,
    parent_id: 3,
  },
  {
    id: 7,
    name: "Терроризмтой тэмцэх зөвлөлийн ажлын алба",
    url: "",
    order: 120,
    type: 1,
    is_active: true,
    parent_id: 1,
  },
  {
    id: 8,
    name: "menu1-2-1",
    url: "",
    order: 121,
    type: 1,
    is_active: false,
    parent_id: 7,
  },
  {
    id: 22,
    name: "extra",
    url: "213",
    order: 123,
    type: 2,
    is_active: false,
    parent_id: 0,
  },
  {
    id: 2,
    name: "Хууль эрх зүй",
    url: "urlll",
    order: 200,
    type: 2,
    is_active: true,
    parent_id: 0,
  },
  {
    id: 6,
    name: "Нэгдэн орсон ОУ-ын гэрээ",
    url: "",
    order: 210,
    type: 3,
    is_active: true,
    parent_id: 2,
  },
  {
    id: 9,
    name: "Мэдээ мэдээлэл",
    url: "",
    order: 300,
    type: 1,
    is_active: true,
    parent_id: 0,
  },
  {
    id: 10,
    name: "Гадаад дотоод мэдээ",
    url: "",
    order: 310,
    type: 2,
    is_active: true,
    parent_id: 9,
  },
  {
    id: 13,
    name: "testing 2 level3 menu",
    url: "",
    order: 312,
    type: 3,
    is_active: true,
    parent_id: 10,
  },
  {
    id: 12,
    name: "testing level3 menu",
    url: "",
    order: 313,
    type: 3,
    is_active: false,
    parent_id: 10,
  },
  {
    id: 11,
    name: "Дүн шинжилгээ",
    url: "",
    order: 400,
    type: 3,
    is_active: false,
    parent_id: 0,
  },
  {
    id: 14,
    name: "Терроризмийн нөхцөл байдал",
    url: "",
    order: 500,
    type: 2,
    is_active: true,
    parent_id: 0,
  },
  {
    id: 15,
    name: "Хориг арга хэмжээ",
    url: "",
    order: 600,
    type: 2,
    is_active: false,
    parent_id: 0,
  },
  {
    id: 16,
    name: "Салбар зөвлөл",
    url: "",
    order: 700,
    type: 3,
    is_active: false,
    parent_id: 0,
  },
  {
    id: 17,
    name: "menu-7-1",
    url: "",
    order: 710,
    type: 2,
    is_active: true,
    parent_id: 16,
  },
  {
    id: 18,
    name: "menu-7-1-1",
    url: "",
    order: 711,
    type: 1,
    is_active: false,
    parent_id: 17,
  },
  {
    id: 19,
    name: "holboo barih",
    url: "uurrll",
    order: 800,
    type: 2,
    is_active: false,
    parent_id: 0,
  },
  {
    id: 23,
    name: "aasdf",
    url: "asfd",
    order: 900,
    type: 1,
    is_active: true,
    parent_id: 0,
  },
  {
    id: 20,
    name: "dddd1",
    url: "uurrll1",
    order: 8001,
    type: 1,
    is_active: false,
    parent_id: 19,
  },
];
